CREATE TABLE CargoFormacoes(
Id BIGINT NOT NULL IDENTITY (1, 1),
IdCargo BIGINT NOT NULL,
IdCurso BIGINT NOT NULL,

CONSTRAINT PKIdCargoFormacao PRIMARY KEY (Id),
CONSTRAINT UKCargoIdCargo UNIQUE (IdCargo),
CONSTRAINT UKCursoIdCurso UNIQUE (IdCurso));
