insert into Estado (Nome, SiglaUF) values ('Acre', 'AC');
insert into Estado (Nome, SiglaUF) values ('Alagoas', 'AL');
insert into Estado (Nome, SiglaUF) values ('Amapá', 'AP');
insert into Estado (Nome, SiglaUF) values ('Amazonas', 'AM');
insert into Estado (Nome, SiglaUF) values ('Bahia', 'BA');
insert into Estado (Nome, SiglaUF) values ('Ceará', 'CE');
insert into Estado (Nome, SiglaUF) values ('Distrito Federal', 'DF');
insert into Estado (Nome, SiglaUF) values ('Espírito Santo', 'ES');
insert into Estado (Nome, SiglaUF) values ('Goiás', 'GO');
insert into Estado (Nome, SiglaUF) values ('Maranhão', 'MA');
insert into Estado (Nome, SiglaUF) values ('Mato Grosso', 'MT');
insert into Estado (Nome, SiglaUF) values ('Mato Grosso do Sul', 'MS');
insert into Estado (Nome, SiglaUF) values ('Minas Gerais', 'MG');
insert into Estado (Nome, SiglaUF) values ('Pará', 'PA');
insert into Estado (Nome, SiglaUF) values ('Paraíba', 'PB');
insert into Estado (Nome, SiglaUF) values ('Paraná', 'PR');
insert into Estado (Nome, SiglaUF) values ('Pernambuco', 'PE');
insert into Estado (Nome, SiglaUF) values ('Piauí', 'PI');
insert into Estado (Nome, SiglaUF) values ('Rio de Janeiro', 'RJ');
insert into Estado (Nome, SiglaUF) values ('Rio Grande do Norte', 'RN');
insert into Estado (Nome, SiglaUF) values ('Rio Grande do Sul', 'RS');
insert into Estado (Nome, SiglaUF) values ('Rondônia', 'RO');
insert into Estado (Nome, SiglaUF) values ('Roraima', 'RR');
insert into Estado (Nome, SiglaUF) values ('Santa Catarina', 'SC');
insert into Estado (Nome, SiglaUF) values ('São Paulo', 'SP');
insert into Estado (Nome, SiglaUF) values ('Sergipe', 'SE');
insert into Estado (Nome, SiglaUF) values ('Tocantins', 'TO');